### ISSUE TITLE
use updated URL for wkhtmltopdf downloads

### ISSUE THREAD

**Issue by ashkulz** [Woorank/pdf-reactor#7]
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:

* Dockerfile

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

**Comment by tzi** [comment]
The URL seems to be [updated](https://github.com/Woorank/pdf-reactor/blob/8866bb82ff707c4140cbf31f54a80aa69d9c0ad6/Dockerfile#L14)

So the issue could certainly be closed.

**Comment by OlivierCuyp** [comment]
@tzi & @ashkulz Thanks, I should have followed this up earlier. Closing the issue.
